services:
  mongo:
    image: batchlcwd/chatback:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://chatOnUser:23042003amt@mongo:27017/admin
    depends_on:
      - mongo
    networks:
      - app-network
    ports:
      - "8080:8080"

volumes:
  mongo-db:

networks:
  app-network:

##version: '3.8'
#
#services:
#  mongo:
#    image: mongo:5.0
#    container_name: mongodb
#    ports:
#      - "27018:27017"
#    volumes:
#      - mongo-db:/data/db
#    networks:
#      - app-network
#
#  boot-app:
#    image: batchlcwd/chatback
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://chatOnUser:23042003amt@mongo:27017/admin
#    depends_on:
#      - mongo
#    networks:
#      - app-network
#
#volumes:
#  mongo-db:
#
#networks:
#  app-network:
